import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { keccak256, toUtf8Bytes } from "ethers";
import {
  canonicalJson,
  computeReportHash,
  hashStep,
  merkleRoot,
  parseAttestationInput,
  verifyReportLocally,
} from "../src/hashing.js";

// These vectors were generated by member4 calling member3, not by this SDK.
function fixture(name = "seven-step-report.json") {
  return JSON.parse(readFileSync(new URL(`../fixtures/${name}`, import.meta.url), "utf8"));
}

const BAD_HASH = `0x${"a".repeat(64)}`;

describe("SDK 0.2 seven-step backend protocol", () => {
  it("verifies the authoritative backend report and exposes chain and manifest checks", () => {
    const result = verifyReportLocally(fixture());
    assert.equal(result.computedReportHash, "0x98265bfbf5ba86ba364be6f52801db3ca058b66cffa938c9f811e6286050df95");
    assert.equal(result.computedMerkleRoot, "0x0ed187aff0d0e6e9a190fea4ac458b1986e38969faee732b4f0acac3586fa64f");
    assert.equal(result.isLocallyValid, true);
    assert.ok("isStepChainValid" in result);
    assert.equal(result.isStepChainValid, true);
    assert.ok("isManifestValid" in result);
    assert.equal(result.isManifestValid, true);
  });

  it("accepts the backend fractional lockup report without losing its 0.5 value", () => {
    const report = fixture("fractional-report.json");
    assert.equal(report.proof_data.steps[2].output.lockup_years, 0.5);
    assert.equal(verifyReportLocally(report).isLocallyValid, true);
    assert.equal(computeReportHash(report), report.proof_data.report_hash);
  });

  it("serializes small decimal exponents like the Python producer", () => {
    assert.equal(canonicalJson({ small: 1e-7, lockup: 0.5, boundary: 1e-4, exponent: 1e-5 }),
      '{"boundary":0.0001,"exponent":1e-05,"lockup":0.5,"small":1e-07}');
  });

  for (const vector of fixture("python-number-vectors.json") as { value: number; canonical: string }[]) {
    it(`matches the Python numeric vector ${vector.canonical}`, () => {
      assert.equal(canonicalJson(vector.value), vector.canonical);
    });
  }

  it("excludes only the self-referential report_hash and commits all other proof fields", () => {
    const report = fixture();
    const original = computeReportHash(report);
    report.proof_data.report_hash = BAD_HASH;
    assert.equal(computeReportHash(report), original);
    delete report.proof_data.report_hash;
    assert.equal(computeReportHash(report), original);
    report.proof_data.manifest_step_hash = BAD_HASH;
    assert.notEqual(computeReportHash(report), original);
  });

  it("uses all seven ordered leaves instead of only the three AI leaves", () => {
    const report = fixture();
    assert.equal(report.proof_data.step_hashes.length, 7);
    assert.equal(merkleRoot(report.proof_data.step_hashes), report.proof_data.merkle_root);
    assert.notEqual(merkleRoot(report.proof_data.reasoning_step_hashes), report.proof_data.merkle_root);
    assert.equal(verifyReportLocally(report).isMerkleRootValid, true);
  });

  it("extracts the existing three contract arguments after full protocol verification", () => {
    const report = fixture();
    assert.deepEqual(parseAttestationInput(report), {
      reportHash: report.proof_data.report_hash,
      merkleRoot: report.proof_data.merkle_root,
      riskScore: 85,
    });
  });

  const chainMutations: [string, (report: any) => void][] = [
    ["step input", r => { r.proof_data.steps[1].input.chain_id = 1; }],
    ["step output", r => { r.proof_data.steps[1].output.team_wallet_pct = 1; }],
    ["input hash", r => { r.proof_data.steps[1].input_hash = BAD_HASH; }],
    ["output hash", r => { r.proof_data.steps[1].output_hash = BAD_HASH; }],
    ["canonical hash content", r => { r.proof_data.steps[1].hash_content += " "; }],
    ["previous step link", r => { r.proof_data.steps[2].previous_step_hash = BAD_HASH; }],
    ["timestamp", r => { r.proof_data.steps[2].timestamp += 1; }],
    ["timestamp_ms", r => { r.proof_data.steps[2].timestamp_ms += 1; }],
    ["step order", r => { [r.proof_data.steps[1], r.proof_data.steps[2]] = [r.proof_data.steps[2], r.proof_data.steps[1]]; }],
    ["source", r => { r.proof_data.steps[2].source = "BACKEND"; }],
    ["step index", r => { r.proof_data.steps[2].step_index = 99; }],
    ["step task identity", r => { r.proof_data.steps[2].task_id = "different-task"; }],
  ];

  for (const [name, mutate] of chainMutations) {
    it(`rejects modified ${name} even after recomputing the outer report hash`, () => {
      const report = fixture();
      mutate(report);
      report.proof_data.report_hash = computeReportHash(report);
      const result = verifyReportLocally(report);
      assert.equal(result.isReportHashValid, true);
      assert.equal(result.isLocallyValid, false);
      assert.ok("isStepChainValid" in result);
      assert.equal(result.isStepChainValid, false);
      assert.throws(() => parseAttestationInput(report));
    });
  }

  const manifestMutations: [string, (report: any) => void][] = [
    ["report body committed by the manifest", r => { r.summary.verdict = "changed verdict"; }],
    ["manifest payload hash", r => { r.proof_data.report_payload_hash = BAD_HASH; }],
    ["manifest step hash", r => { r.proof_data.manifest_step_hash = BAD_HASH; }],
    ["AI compatibility hash view", r => { r.proof_data.reasoning_step_hashes[0] = BAD_HASH; }],
    ["backend compatibility hash view", r => { r.proof_data.backend_step_hashes[0] = BAD_HASH; }],
    ["ordered leaf view", r => { r.proof_data.step_hashes.reverse(); }],
  ];

  for (const [name, mutate] of manifestMutations) {
    it(`rejects modified ${name} after recomputing the outer hash`, () => {
      const report = fixture();
      mutate(report);
      report.proof_data.report_hash = computeReportHash(report);
      const result = verifyReportLocally(report);
      assert.equal(result.isReportHashValid, true);
      assert.equal(result.isLocallyValid, false);
      assert.throws(() => parseAttestationInput(report));
    });
  }

  for (const field of ["hash_algorithm", "hash_version", "manifest_version"]) {
    for (const unsupported of ["unsupported", undefined]) {
      it(`rejects ${unsupported === undefined ? "missing" : "unknown"} ${field}`, () => {
        const report = fixture();
        if (unsupported === undefined) delete report.proof_data[field];
        else report.proof_data[field] = unsupported;
        report.proof_data.report_hash = computeReportHash(report);
        assert.throws(() => parseAttestationInput(report));
      });
    }
  }

  it("refuses an incomplete chain even when its leaf root and report hash are recomputed", () => {
    const report = fixture();
    report.proof_data.steps.pop();
    report.proof_data.step_hashes.pop();
    report.proof_data.merkle_root = merkleRoot(report.proof_data.step_hashes);
    report.proof_data.report_hash = computeReportHash(report);
    assert.throws(() => parseAttestationInput(report));
  });

  it("refuses a failed workflow instead of treating it as a complete attestation", () => {
    const report = fixture();
    report.proof_data.steps[6].current_step = "FAILED";
    report.proof_data.report_hash = computeReportHash(report);
    assert.throws(() => parseAttestationInput(report));
  });

  it("explicitly refuses legacy three-step reports", () => {
    assert.throws(() => parseAttestationInput(fixture("legacy-report.json")));
  });

  const malformedManifests: [string, (step: any) => void][] = [
    ["ordered step names", step => { step.output.ordered_steps.reverse(); }],
    ["prior step count", step => { step.output.prior_step_count = 5; }],
    ["final step count", step => { step.output.final_step_count = 6; }],
    ["ordered prior hashes", step => { step.input.ordered_prior_step_hashes.reverse(); }],
    ["input payload commitment", step => { step.input.report_payload_hash = BAD_HASH; }],
    ["output payload commitment", step => { step.output.report_payload_hash = BAD_HASH; }],
    ["manifest output version", step => { step.output.manifest_version = "unknown"; }],
  ];

  for (const [name, mutate] of malformedManifests) {
    it(`rejects malformed manifest ${name} even with a self-consistent final step and Merkle root`, () => {
      const report = fixture();
      const last = report.proof_data.steps[6];
      mutate(last);
      // Re-sign only the final step, using the public protocol and its original
      // canonical envelope. The six authoritative prior steps remain untouched.
      last.input_hash = keccak256(toUtf8Bytes(canonicalJson(last.input)));
      last.output_hash = keccak256(toUtf8Bytes(canonicalJson(last.output)));
      const envelope = JSON.parse(last.hash_content);
      envelope.input_hash = last.input_hash;
      envelope.output_hash = last.output_hash;
      last.hash_content = canonicalJson(envelope);
      last.step_hash = hashStep(last.previous_step_hash, last.hash_content, last.timestamp_ms);
      report.proof_data.step_hashes[6] = last.step_hash;
      report.proof_data.backend_step_hashes[3] = last.step_hash;
      report.proof_data.manifest_step_hash = last.step_hash;
      report.proof_data.merkle_root = merkleRoot(report.proof_data.step_hashes);
      report.proof_data.report_hash = computeReportHash(report);

      const result = verifyReportLocally(report);
      assert.equal(result.isReportHashValid, true);
      assert.equal(result.isMerkleRootValid, true);
      assert.equal(result.isStepChainValid, true);
      assert.equal(result.isManifestValid, false);
      assert.equal(result.isLocallyValid, false);
      assert.throws(() => parseAttestationInput(report));
    });
  }

  it("rejects a changed leaf even if its Merkle root and report hash are recomputed", () => {
    const report = fixture();
    report.proof_data.step_hashes[0] = BAD_HASH;
    report.proof_data.merkle_root = merkleRoot(report.proof_data.step_hashes);
    report.proof_data.report_hash = computeReportHash(report);
    const result = verifyReportLocally(report);
    assert.equal(result.isReportHashValid, true);
    assert.equal(result.isMerkleRootValid, true);
    assert.equal(result.isStepChainValid, true);
    assert.equal(result.isManifestValid, false);
    assert.equal(result.isLocallyValid, false);
    assert.throws(() => parseAttestationInput(report));
  });

  for (const field of ["hash_algorithm", "hash_version"]) {
    it(`rejects an unknown individual step ${field}`, () => {
      const report = fixture();
      report.proof_data.steps[2][field] = "unsupported";
      report.proof_data.report_hash = computeReportHash(report);
      const result = verifyReportLocally(report);
      assert.equal(result.isReportHashValid, true);
      assert.equal(result.isMerkleRootValid, true);
      assert.equal(result.isStepChainValid, false);
      assert.equal(result.isLocallyValid, false);
      assert.throws(() => parseAttestationInput(report));
    });
  }
});
